import '@/app/ui/globals.css';
import clsx from 'clsx';
import type { Metadata } from 'next';
import Script from 'next/script';

import { Providers } from '@/app/providers';
import Footer from '@/app/ui/Footer/Footer';
import Header from '@/app/ui/Header/Header';
import { roboto } from '@/app/ui/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(roboto.className, 'bg-gray-50 dark:bg-gray-900')}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
        <Script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js" />
      </body>
    </html>
  );
}
